### ISSUE TITLE
Plugin not loaded

### ISSUE THREAD

**Issue by KhanMaytok** [driftyco/deploy-tutorial#1]
I have an error:  Plugin not loaded when I try execute the update action. Platform is android. I'm not executing on a web browser.

**Comment by Ionitron** [comment]
Greetings @SakyaStelios!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
